### ISSUE TITLE
Docker-Musicbrainz

### ISSUE THREAD

**Issue by boredazfcuk** [boredazfcuk/docker-musicbrainz#1]
Hi, @nodecentral & @Lennong.

I tried replying to the issue on linuxserver/musicbrainz, but by the time I finished typing, they'd archived it so it was read only. Not sure if this will work, as you've not posted to this issue, but it's worth a try.

Anyway, this is the container I've been using. It's on Dockerhub [here](https://hub.docker.com/r/boredazfcuk/musicbrainz). I've had it working since early December, but I actually proxy to it from my nginx container because it's easier to make it look pretty from all devices/containers on my network. I'm not sure what it will look like if you're accessing it directly.

Any tips or bugs found would be welcome.

**Comment by Lennong** [comment]
Hi! Thanks for reaching out! I will check it out and report back as soon I have it up and running.

/Lennart

**Comment by nodecentral** [comment]
Thanks @boredazfcuk , I’ll give it a go..

While I’ve got you, I’ve been playing with a few of your dockers containers, and notice referenced  to your ‘stack’ (Dave) is that something I should look to do/mirror ?

**Comment by nodecentral** [comment]
Does this look right to you..?

````
musicbrainz:
    image: boredazfcuk/musicbrainz
    container_name: musicbrainz
    environment:
      - stack_user=stackman
	  - stack_uid=1000
      - musicbrainz_group=musicbrainz
	  - musicbrainz_group_id=100
      - TZ=Europe/London
	  - app_base_dir=/Musicbrainz
	  - config_dir=/config
      - replication_token=<code from MusicBrainz>
      - WEBADDRESS=192.168.1.234
	  - MUSICBRAINZ_USE_PROXY=0. #0=no?
    volumes:
      - </path/to/appdata/config>:/config
      - </path/to/appdata/config>:/Musicbrainz
    ports:
      - 5000:5000
	  restart: unless-stopped

**Comment by boredazfcuk** [comment]
> Thanks @boredazfcuk , I’ll give it a go..
> 
> While I’ve got you, I’ve been playing with a few of your dockers containers, and notice references to your ‘stack’ (Dave) is that something I should look to do/mirror ?

Ha! No, the stack names were just a way of me classifying what my stacks were for...

Steve was named after Steve from Dodgeball.

Tom peeped on various bits of kit around my house and kept them in check. So notified me of Public IP address changes on my router, switched off my 5.1 system if it had been left on. Switched off the kids TV if they weren't watching Kodi or playing PS4 etc.

Peter - File synchronisation. Coz the only thing I could think of that kept with the first names naming convention was a peado joke.

Dave was named after Dave the Octopus from the Penguins of Madagasgar movie. The stack ran all my Squid traffic monitoring related containers, hence "Dave". I don't actually maintain that stack any more. I have a new one I just went back to a boring name Core because it runs all my core services (basically replaced Dave and Tom).

The reason I just started putting the names on the containers was so that people would know that they are primarily used in a stack, so may not be tested individually.

"Steve" was the original project and it started out because of the pain it was to get everything configured perfectly. The idea being that I can trash my entire config, then "up" the stack and the containers configure themselves to interact with one another. It just grew and grew from there and now there's 18 containers just in a single stack.

**Comment by boredazfcuk** [comment]
> 
> 
> Does this look right to you..?
> 
> ```
> musicbrainz:
>     image: boredazfcuk/musicbrainz
>     container_name: musicbrainz
>     environment:
>       - stack_user=stackman
>       - stack_uid=1000
>       - musicbrainz_group=musicbrainz
>       - musicbrainz_group_id=100
>       - TZ=Europe/London
>       - app_base_dir=/Musicbrainz
>       - config_dir=/config
>       - replication_token=<code from MusicBrainz>
>       - WEBADDRESS=192.168.1.234
>       - MUSICBRAINZ_USE_PROXY=0. #0=no?
>     volumes:
>       - </path/to/appdata/config>:/config
>       - </path/to/appdata/config>:/Musicbrainz
>     ports:
>       - 5000:5000
> 	  restart: unless-stopped
> ```

Nearly there... The WEBADDRESS variable is a funny one (it should also be **web_address**). This is why I run it behind an nginx proxy. Say the host machine is on the local network as `server1` then you'd set it to `server1:5000`. From your laptop or whatever, you'd then go to `http://server1:5000` and it should all look pretty. If this bit is wrong, then the page will look terrible as non of the fancy page scripting will work. The links and buttons will still be there, but there won't be any pictures or thumbnails and the formatting will just look completely wrong. I've not tried it with a static IP but I guess it will work if you only access the device using that IP and not its network name.

I'd just get rid of this one: MUSICBRAINZ_USE_PROXY and you probably won't need to set stack_user, stack_uid, musicbrainz_group, app_base_dir or config_dir as they all look like the default settings.

`</path/to/appdata/config>:/Musicbrainz` that bit doesn't look right though. It should be something like: `</path/to/appdata/data>:/data`

FYI, my stack is configured like this:

```
   musicbrainz:
      hostname: musicbrainz
      networks:
         containers:
            aliases:
               - musicbrainz
      env_file:
         - timezone.env
         - musicbrainz.env
      image: boredazfcuk/musicbrainz
      healthcheck:
         test: /usr/local/bin/healthcheck.sh
         start_period: 15s
      restart: always
      volumes:
         - steve_musicbrainz_config:/config
         - /home/musicbrainz/MusicBrainz_DB/:/data
```

With `timezone.env` containing:
```
# Set the timezone for all containers
TZ=Europe/London
```
and `musicbrainz.env` containing:
```
# Musicbrainz variables
replication_token=H123999D
web_address=musicbrainz:5000
MUSICBRAINZ_USE_PROXY=1
```

**Comment by nodecentral** [comment]
> Steve was named after Steve from Dodgeball.
> Dave was named after Dave the Octopus from the Penguins of Madagasgar movie.

Love it !

**Comment by boredazfcuk** [comment]
It's fine, just quirks of different systems.

You'll definitely want some sort of persistent volume mapped for `/home/musicbrainz/MusicBrainz_DB/:/data` though.

That's where the DB is stored and also where it keeps the downloaded Db export that it imports during initialisation. If that isn't persistent, each time the container is re-created, it'll need to download the Db export and import to the Db again... 

The import task takes hours on my server which is an i5/16GB/SSD home built NAS so not exactly a slouch. So yeah, persisting the /data folder will save hours of time.
