### ISSUE TITLE
Failed to start import of DB

### ISSUE THREAD

**Issue by thel1988** [boredazfcuk/docker-musicbrainz#2]
Hi

When I try to import this, i get the following error during startup:

```
Wed Aug  4 22:27:09 2021 : Pre-checking /data/mbdump/mbdump-cdstubs.tar.bz2
Wed Aug  4 22:27:09 2021 : Schema sequence mismatch - codebase is 25, /data/mbdump/mbdump-cdstubs.tar.bz2 is 26

Failed to import dataset.
```

Is there an update needed for this?

**Comment by boredazfcuk** [comment]
Hi,

It looks like they've updated the database schema in May this year.

Instructions on how to upgradee live here: https://blog.metabrainz.org/2021/05/18/musicbrainz-schema-change-release-2021-05-17-with-upgrade-instructions/. Although, I'm not sure if you'll have much luck with that.

I'll need to rebuild the Dockerfile and Image, but that will likely take me a while. The last time I tried rebuilding with newer versions of everything, the postgresql version had been updated and the musicbrainz code didn't work with it. Hopefully that's not an issue any more.

It might take me a while, as the builds take ages, so testing is slow.

**Comment by boredazfcuk** [comment]
Hi,

Well, I rebuilt the container and everything just worked first time... I was not expecting that!

Also, because of the database schema change, you'll need to basically blow away your entire config. I removed the `musicbrainz`, `nginx`, `postgres` and `redis` folders in my config volume and also the `mbdump`, musicbrainz_db` and `redis` folders from the data volume.

Deployed the image and booted it overnight, was working when I checked it this morning.

I've pushed a new image to Dockerhub, only to realise that I've not built it for arm64, only amd64, so if you're running this on an arm device, don't upgrade just yet. Kicking off the arm build now, that one takes a while, because I'm building it in an emulator.

Thanks.

**Comment by thel1988** [comment]
Im not sure i see the new docker image on docker hub it seems the one i Can see on docker hub is 4 days Old which is the one I already have.

**Comment by boredazfcuk** [comment]
Ahh yes. I've just checked my DockerHub release script which builds and pushes all 20(ish) of my containers, and I've commented out the Musicbrainz container.

I guess that's probably a good thing though, as the image there wouldn't have contained the arm64 image and any users who are automatically updating via watchdog (if there actually are any lol), would have had their installations upgrade, only to error out.

It's going to be quite a while before this completes though. I've kicked off my automated build script, but it's building a Dockerised version of a custom compiled Kodi on arm64 platform, which is taking a fair while... It's currently sat at 31% complete, and it's been running for 3h 30mins.

Once it's completed that, it will move on to building Musicbrainz. Probably looking 12-24hrs before the updated Musicbrainz image hits Dockerhub.

**Comment by thel1988** [comment]
Fair enough will wait 😊

**Comment by boredazfcuk** [comment]
Hi, the Kodi build took about 14 hours in the end. Crazy.

I kicked off the Musicbrainz build before I went to bed and it was done by the morning. I pushed the new versions of my containers to Dockerhub before I left for work this morning. I think Musicbrainz finished uploading about 10mins ago.

Remove all the contents of your config and data volumes, re-create the container and you should be golden.

**Comment by thel1988** [comment]
Sorry but the latest image on dockerhub is now 14 days Old. Can you recheck?

**Comment by boredazfcuk** [comment]
Hmmm. Looks like I've messed up the tagging logic when I updated my script. I was tagging it with my local registry, rather than the Dockerhub registry, so uploaded it to the wrong place.

Just pushing it now... Shouldn't be long.

Thanks.

**Comment by thel1988** [comment]
Awesome looking forward to it :D

**Comment by boredazfcuk** [comment]
Sorry, it's taking longer than expected. I run all my containers on a low power 2-core i3 2.2ghz NAS device. When I kick off a build, it wakes up an i5 3.4ghz 4-core server and runs the build on that.

The server keeps falling back to sleep before the build/upload completes for some reason.

**Comment by boredazfcuk** [comment]
It's there now
